name: Docker Image DevSecOps CI

on:
  push:
    branches: [ "feature/github-actions" ]
  pull_request:
    branches: [ "feature/github-actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
#      with:
#        # Additional arguments to the Sonar Scanner CLI
#        args: # optional
#        # Set the sonar.projectBaseDir analysis property
#        projectBaseDir: # optional
#        # Version of the Sonar Scanner CLI to use
#        scannerVersion: # optional, default is 6.2.1.4610
#        # URL to download the Sonar Scanner CLI binaries from
#        scannerBinariesUrl: # optional, default is https://binaries.sonarsource.com/Distribution/sonar-scanner-cli
