name: Docker Image DevSecOps CI

on:
  push:
    branches: [ "feature/github-actions" ]
  pull_request:
    branches: [ "feature/github-actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  sonarqube:
    name: SonarQube Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#        # Additional arguments to the Sonar Scanner CLI
#        args: # optional
#        # Set the sonar.projectBaseDir analysis property
#        projectBaseDir: # optional
#        # Version of the Sonar Scanner CLI to use
#        scannerVersion: # optional, default is 6.2.1.4610
#        # URL to download the Sonar Scanner CLI binaries from
#        scannerBinariesUrl: # optional, default is https://binaries.sonarsource.com/Distribution/sonar-scanner-cli
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      -  uses: actions/checkout@v4
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
